/* ===== Recorded runs: replayed through the same foundation and gatekeeper ===== */
const L = o => JSON.stringify(o);
const RECORDED = [
  { name: 'Prep me for my call with Alex tomorrow', requester: 'EMP-PRIYA', text: 'Prep me for my call with Alex tomorrow',
    orch: [
      L({ k: 'decision', type: 'requester', title: 'Priya Shah, Sales, covers Alex', detail: 'Wholesaler on Alex Rivera’s coverage team, so relationship notes and her own coaching notes are in bounds.' }),
      L({ k: 'decision', type: 'intent', title: 'Meeting prep, not new research', detail: 'She needs a brief for the call. Alex’s open decision is whether GFA stays in his growth model before the Oct 1 committee.', intent: 'meeting_prep' }),
      L({ k: 'decision', type: 'entity', title: 'Alex → Alex Rivera, Morgan Stanley', detail: 'One graph match. The growth-model unit is active: it holds the open decision and the last call.', advisor: 'ADV-101', unit: 'BU-101A', confidence: 'high' }),
      L({ k: 'decision', type: 'scope', title: 'Growth model unit only (BU-101A)', detail: 'The 401(k) committee unit is out of scope; nothing from it should shape this call.' }),
      L({ k: 'decision', type: 'known', title: 'Reuse K-201 and Alex’s preferences', detail: 'K-201 already explains why GFA trailed. Memory holds his format and fee preferences, so no re-research.', uses: ['K-201', 'MEM-011', 'MEM-017', 'MEM-014', 'CALL-0922', 'TASK-301'] }),
      L({ k: 'decision', type: 'missing', title: 'Dollar costs aren’t stored yet', detail: 'Alex wants fees in dollars on $38M. Tool Selection computes them on the model platform instead of estimating.' }),
      L({ k: 'decision', type: 'memory', title: 'Read only: nothing new to remember', detail: 'Priya’s request contains no new statement from Alex, so memory is read, not changed.', class: 'read_only' }),
      L({ k: 'decision', type: 'controls', title: 'Internal brief, every number traced', detail: 'No send. Personal note allowed for the relationship team; coaching visible to Priya only; numbers only from the platform.' }),
      L({ k: 'task', id: 'T1', agent: 'product.tools', title: 'Cost Alex’s $38M across three funds', objective: 'Compute annual costs on $38M for GFFFX, VWUAX and VIGAX, and the blended cost of 70% VIGAX with 30% GFA', depends_on: [], reads: ['knowledge'], tools: ['models.cost_on_assets', 'models.portfolio_construction'], why: 'Only the model platform may produce dollar figures.' }),
      L({ k: 'task', id: 'T2', agent: 'sales.schedule', title: 'Confirm Alex’s call time', objective: 'Confirm the call time against Alex’s meeting pattern', depends_on: [], reads: ['memory'], tools: ['calendar.find_times'], why: 'Alex books through Jamie at 7:30 a.m. PT on Tuesdays or Thursdays.' }),
      L({ k: 'task', id: 'T3', agent: 'sales.prep', title: 'Prepare Alex meeting brief', objective: 'Build Priya’s one-page brief from K-201, Alex’s preferences and T1’s numbers', depends_on: ['T1', 'T2'], reads: ['memory', 'knowledge', 'models', 'policy'], tools: ['crm.get_opportunities'], why: 'Prep Me owns briefs and may use relationship notes.' }),
      L({ k: 'decision', type: 'success', title: 'Priya walks in with one page', detail: 'Dollar costs, the verified why, the open decision and logistics. Alex repeats nothing.' }),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.cost_on_assets', { tickers: ['GFFFX', 'VWUAX', 'VIGAX'], amount_usd: 38000000 }], ['models.portfolio_construction', { weights: { VIGAX: 70, GFFFX: 30 } }]],
        json: { says: 'I ran the model platform instead of estimating. On $38M, GFA F-2 costs about $152,000 a year, VWUAX $95,000 and VIGAX $19,000; a 70/30 VIGAX and GFA mix blends to 0.155%.',
          output: { kind: 'finding', title: 'Costs on Alex’s $38M', body: '- GFA F-2 (GFFFX): 0.40%, about $152,000 a year\n- Vanguard U.S. Growth (VWUAX): 0.25%, about $95,000\n- Vanguard Growth Index (VIGAX): 0.05%, about $19,000\n\n70% VIGAX + 30% GFA blends to 0.155%.' },
          used: ['GFFFX', 'VWUAX', 'VIGAX'], knowledge: [{ label: 'Annual fund costs on $38M for Alex Rivera', value: 'GFFFX $152,000; VWUAX $95,000; VIGAX $19,000 a year. 70/30 VIGAX/GFA blend: 0.155%.', evidence: ['models.cost_on_assets', 'models.portfolio_construction'] }], memory: [], commitments: [], needs_approval: false, open_questions: [] } },
      T2: { calls: [['calendar.find_times', { advisor_id: 'ADV-101' }]],
        json: { says: '“Tomorrow” is Wednesday, but Alex takes calls on Tuesdays and Thursdays and books through Jamie. I proposed Thursday at 7:30 a.m. PT, before his committee, and flagged the mismatch.',
          output: { kind: 'note', title: 'Call time', body: 'Proposed: Thu Oct 1, 7:30 a.m. PT on Teams, before his committee.\nBackup: Tue Oct 6, 7:30 a.m. PT.\nBook through Jamie Cho.' },
          used: ['MEM-012'], knowledge: [], memory: [], commitments: [{ title: 'Confirm the Thursday 7:30 a.m. call with Jamie Cho', owner: 'Priya Shah', due: 'Sep 30' }], needs_approval: false, open_questions: ['Is tomorrow’s call already booked, or should Jamie move it to Thursday?'] } },
      T3: { calls: [['crm.get_opportunities', { advisor_id: 'ADV-101' }]],
        json: { says: 'I reused QAR’s K-201 and Tool Selection’s dollar figures instead of redoing research, and kept it to one page because that is how Alex works.',
          output: { kind: 'brief', title: 'Brief: Alex Rivera, growth model decision', body: 'Open with: his marathon training for December.\n\nThe decision: keep or replace GFA in the new growth model. Committee meets Oct 1 (OPP-501, Proposal).\n\nLead with dollars on $38M:\n- GFA F-2 about $152,000 a year; VWUAX about $95,000; VIGAX about $19,000\n- 70/30 VIGAX and GFA blends to 0.155%\n\nWhy GFA trailed (K-201): mandate, concentration, cost.\n\nStill owed: quarterly attribution in his one-page format (TASK-301).' },
          used: ['K-201', 'MEM-011', 'MEM-017', 'MEM-014', 'MEM-015', 'TASK-301', 'OPP-501'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [] } }
    } },
  { name: 'Create an ETF email campaign for Sofia', requester: 'EMP-MARCUS', text: 'Create an ETF email campaign for Sofia',
    orch: [
      L({ k: 'decision', type: 'requester', title: 'Marcus Bell, Marketing', detail: 'Marketing may draft advisor emails. Personal and coaching notes are not available to Marketing.' }),
      L({ k: 'decision', type: 'intent', title: 'One advisor email, not a mass campaign', detail: '“Campaign for Sofia” targets one advisor, so this is a personalized email draft with approval.', intent: 'content' }),
      L({ k: 'decision', type: 'entity', title: 'Sofia → Sofia Martinez, Morgan Stanley', detail: 'One graph match; her only unit is the core model portfolios.', advisor: 'ADV-104', unit: 'BU-104', confidence: 'high' }),
      L({ k: 'decision', type: 'scope', title: 'Martinez core model portfolios (BU-104)', detail: 'Her stated priority lives in this unit.' }),
      L({ k: 'decision', type: 'known', title: 'She said she’s moving core to ETFs', detail: 'MEM-041 is her own statement (CALL-0915). MEM-013 says Morgan Stanley blocks links, so send a PDF.', uses: ['MEM-041', 'MEM-042', 'MEM-013', 'CALL-0915', 'TASK-303'] }),
      L({ k: 'decision', type: 'missing', title: 'Interest in our ETFs isn’t stated', detail: 'She never asked about Capital Group ETFs. Lead with her question about where active managers fit.' }),
      L({ k: 'decision', type: 'memory', title: 'Marcus’s ask is not Sofia’s preference', detail: 'Wanting an ETF email tells us about Marketing’s plan, not about Sofia (POL-6). Nothing new to remember.', class: 'read_only' }),
      L({ k: 'decision', type: 'controls', title: 'Draft only; compliance and approval', detail: 'Legal & Compliance reviews; nothing is sent without approval; it goes out under Priya’s name as a PDF attachment, not a link.' }),
      L({ k: 'task', id: 'T1', agent: 'marketing.gather', title: 'Pick approved ETF content', objective: 'Find approved Seismic content on ETFs and on where active management fits in core-satellite', depends_on: [], reads: ['knowledge', 'policy'], tools: ['seismic.search_content'], why: 'Only approved content can be used.' }),
      L({ k: 'task', id: 'T2', agent: 'marketing.email', title: 'Draft Sofia’s email', objective: 'Draft a short email to Sofia answering her core-satellite question, attaching the approved pieces', depends_on: ['T1'], reads: ['memory', 'knowledge', 'policy'], tools: ['mail.draft'], why: 'Personalized Email writes advisor emails.' }),
      L({ k: 'task', id: 'T3', agent: 'marketing.legal', title: 'Review Sofia’s email', objective: 'Review the draft’s claims and add the required disclosures', depends_on: ['T2'], reads: ['policy', 'knowledge'], tools: ['sharepoint.get_disclosures'], why: 'Nothing client-facing leaves without review.' }),
      L({ k: 'decision', type: 'success', title: 'An email Sofia would actually want', detail: 'Answers her stated question, uses approved content, PDF not link, waiting for approval.' }),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['seismic.search_content', { query: 'etf core satellite active' }]],
        json: { says: 'Two approved pieces fit: the core-satellite guide answers her question directly, and the ETF lineup overview covers the product side.',
          output: { kind: 'content_pick', title: 'Approved content for Sofia', body: '- SEIS-117 Core-satellite: where active management fits (lead piece)\n- SEIS-120 Capital Group ETF lineup overview (supporting)\n\nNot used: SEIS-118 is public-audience content.' },
          used: ['SEIS-117', 'SEIS-120', 'MEM-041'], knowledge: [], memory: [{ attribute: 'Investment style', value: 'Prefers passive investing', scope: 'BU-104', category: 'priority', basis: 'inference', evidence: [] }], commitments: [], needs_approval: false, open_questions: [] } },
      T2: { calls: [['mail.draft', { to: 'Sofia Martinez', subject: 'Where active managers fit in your core-satellite model' }]],
        json: { says: 'I answered the question Sofia actually asked, attached the approved pieces as PDFs because Morgan Stanley blocks links, and kept it short for an evening read.',
          output: { kind: 'email', title: 'Where active managers fit in your core-satellite model', body: 'Hi Sofia,\n\nYou mentioned you’re moving more of your core to ETFs this year and asked what active managers still add. Two short pieces may help:\n\n- Core-satellite: where active management fits (3 pages)\n- Capital Group ETF lineup overview (2 pages)\n\nBoth are attached as PDFs. Happy to walk through them whenever suits you.\n\nPriya' },
          used: ['MEM-041', 'MEM-042', 'MEM-013', 'SEIS-117', 'SEIS-120', 'CALL-0915'], knowledge: [], memory: [{ attribute: 'Interest in Capital Group ETFs', value: 'Interested in Capital Group ETFs', scope: 'BU-104', category: 'priority', basis: 'employee_request', evidence: [] }], commitments: [], needs_approval: true, open_questions: [] } },
      T3: { calls: [['sharepoint.get_disclosures', { content_type: 'advisor email' }]],
        json: { says: 'No performance or fee figures, no personal notes, approved content only. I added the required disclosure. It needs approval before it goes out under Priya’s name.',
          output: { kind: 'note', title: 'Review: email to Sofia', body: '- Claims: none beyond approved content\n- Numbers: none\n- Personal notes: none\n- Disclosure added: For financial professional use only.\n\nResult: ready to send once approved.' },
          used: ['POL-1', 'POL-4', 'SEIS-117', 'SEIS-120'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [] } }
    } }
];

RECORDED.push(
  { name: 'Identify the growing trends in LA territory', requester: 'EMP-PRIYA', text: 'Identify the growing trends in LA territory',
    orch: [
      L({ k: 'decision', type: 'requester', title: 'Priya Shah, Sales, Southern California', detail: 'Her territory includes LA; she covers two of its three advisors and Sam covers all three.' }),
      L({ k: 'decision', type: 'intent', title: 'Territory review, not one advisor', detail: 'She wants what is growing across LA so she can decide where to spend time and what to bring.', intent: 'research' }),
      L({ k: 'decision', type: 'entity', title: 'LA territory: Daniel, Rachel, Luis', detail: 'No single advisor. Territory context comes from the graph; personal notes stay out.', advisor: null, unit: null, territory: 'LA', confidence: 'high' }),
      L({ k: 'decision', type: 'scope', title: 'Three LA advisors, shared records only', detail: 'Stated priorities, recorded conversations and open opportunities; no private or personal notes.' }),
      L({ k: 'decision', type: 'known', title: 'Each advisor’s own stated priority', detail: 'Memory already holds what each LA advisor said this quarter; the trends model counts them.', uses: ['MEM-051', 'MEM-061', 'MEM-071', 'CALL-0918', 'CALL-0923', 'EMAIL-0925'] }),
      L({ k: 'decision', type: 'missing', title: 'No market-wide flow data', detail: 'Trends come from our own recorded conversations and opportunities. They are signals, not market statistics.' }),
      L({ k: 'decision', type: 'memory', title: 'Read only', detail: 'A territory question adds nothing new about any advisor.', class: 'read_only' }),
      L({ k: 'decision', type: 'controls', title: 'Signals labeled as signals', detail: 'Model outputs are shown with their evidence; fund numbers only from the data platform.' }),
      L({ k: 'task', id: 'T1', agent: 'sales.territory', title: 'Summarize LA territory trends', objective: 'Run the territory trends model for LA and explain what is growing, with evidence', depends_on: [], reads: ['memory', 'models'], tools: ['models.territory_trends'], why: 'Territory Planning owns territory reviews.' }),
      L({ k: 'task', id: 'T2', agent: 'product.qar', title: 'Verify BFA and AMBAL facts', objective: 'Pull verified facts for the funds that fit the top trends: BFA and AMBAL', depends_on: ['T1'], reads: ['knowledge'], tools: ['fund.lookup', 'mstar.get_peers'], why: 'Numbers must come from the data platform.' }),
      L({ k: 'task', id: 'T3', agent: 'marketing.gather', title: 'Pick content for LA trends', objective: 'Find approved content that matches the top LA trends', depends_on: ['T1'], reads: ['knowledge', 'policy'], tools: ['seismic.search_content'], why: 'Only approved content can be shared.' }),
      L({ k: 'decision', type: 'success', title: 'Priya knows where to focus in LA', detail: 'What is growing, who is driving it, which funds and approved pieces fit.' }),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.territory_trends', { territory: 'LA' }]],
        json: { says: 'I ran the territory model on what LA advisors actually told us this quarter. Fixed income is the clearest shift: two advisors raised it, none did last quarter.',
          output: { kind: 'finding', title: 'What is growing in LA', body: '- Core bonds and fixed income: 2 advisors, up from none (Rachel Okafor, Luis Herrera)\n- Fee scrutiny: 2 advisors, up from 1 (Daniel Kim, Luis Herrera)\n- Retirement income: 1 advisor, new this quarter (Rachel Okafor)\n- ETF and model-portfolio interest: steady (Daniel Kim)\n\nThese are signals from recorded conversations, not market data.' },
          used: ['MEM-061', 'MEM-071', 'MEM-051', 'CALL-0923', 'EMAIL-0925', 'CALL-0918'],
          knowledge: [{ label: 'LA territory trends, this quarter', value: 'Core bonds and fixed income: 2 advisors (0 last quarter). Fee scrutiny: 2 (1). Retirement income: 1 (0). ETF and model portfolios: steady at 1.', evidence: ['models.territory_trends', 'CALL-0923', 'EMAIL-0925', 'CALL-0918'] }],
          memory: [], commitments: [{ title: 'Send Luis Herrera the core bond story', owner: 'Sam Lee', due: 'Oct 9' }], needs_approval: false, open_questions: [] } },
      T2: { calls: [['fund.lookup', { name: 'BFA' }], ['fund.lookup', { name: 'AMBAL' }], ['mstar.get_peers', { category: 'Intermediate Core Bond' }], ['mstar.get_peers', { category: 'Moderate Allocation' }]],
        json: { says: 'Both funds that fit these trends are cheap for their categories. I took every number from the data platform and Morningstar.',
          output: { kind: 'finding', title: 'Funds that fit LA’s top trends', body: '- The Bond Fund of America F-2 (ABNFX): 0.34%, vs. a 0.46% Intermediate Core Bond median\n- American Balanced Fund F-2 (AMBFX): 0.35%, vs. a 0.9% Moderate Allocation median\n\nBFA fits Luis’s move into fixed income; AMBAL and BFA both fit Rachel’s income review.' },
          used: ['ABNFX', 'AMBFX', 'MEM-061', 'MEM-071'],
          knowledge: [{ label: 'BFA and AMBAL F-2 cost vs. category', value: 'ABNFX 0.34% vs. 0.46% Intermediate Core Bond median; AMBFX 0.35% vs. 0.9% Moderate Allocation median.', evidence: ['ABNFX', 'AMBFX', 'mstar.get_peers'] }],
          memory: [], commitments: [], needs_approval: false, open_questions: [] } },
      T3: { calls: [['seismic.search_content', { query: 'bond fixed income balanced income retirees' }]],
        json: { says: 'Three approved pieces line up with the trends, one per conversation Priya or Sam will have.',
          output: { kind: 'content_pick', title: 'Approved content for LA', body: '- SEIS-121 The Bond Fund of America: core bond story (for Luis)\n- SEIS-123 Balanced vs. bond funds in a retirement income plan (for Rachel)\n- SEIS-122 American Balanced Fund overview (supporting)\n\nAll approved for financial professionals.' },
          used: ['SEIS-121', 'SEIS-122', 'SEIS-123'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [] } }
    } },
  { name: 'Compare BFA and AMBAL for Rachel and schedule a meeting with her next month', requester: 'EMP-PRIYA', text: 'Compare BFA and AMBAL for Rachel and schedule a meeting with her next month',
    orch: [
      L({ k: 'decision', type: 'requester', title: 'Priya Shah covers Rachel', detail: 'Rachel Okafor is on Priya’s coverage list, so shared advisor context is in bounds.' }),
      L({ k: 'decision', type: 'intent', title: 'Fund comparison plus a meeting', detail: 'Two outcomes: a BFA vs. AMBAL comparison framed for Rachel, and a meeting next month.', intent: 'research' }),
      L({ k: 'decision', type: 'entity', title: 'Rachel → Rachel Okafor, UBS', detail: 'One graph match; her retirement income unit is the only one.', advisor: 'ADV-106', unit: 'BU-106', confidence: 'high' }),
      L({ k: 'decision', type: 'scope', title: 'Okafor retirement income portfolios', detail: 'Her stated priority lives here.' }),
      L({ k: 'decision', type: 'known', title: 'She already told us what she needs', detail: 'MEM-061 and CALL-0923: reliable income for retirees; she is reviewing balanced and bond funds.', uses: ['MEM-061', 'CALL-0923', 'OPP-505', 'SEIS-123'] }),
      L({ k: 'decision', type: 'missing', title: 'No amount given: show cost per $1M', detail: 'Assumption stated; Tool Selection computes it on the model platform.' }),
      L({ k: 'decision', type: 'memory', title: 'Read only', detail: 'Her need is already in memory in her own words; nothing new to store.', class: 'read_only' }),
      L({ k: 'decision', type: 'controls', title: 'Internal comparison; invite needs approval', detail: 'Numbers only from the platform; the meeting is a tentative hold until Priya approves the invite.' }),
      L({ k: 'task', id: 'T1', agent: 'product.tools', title: 'Cost BFA vs. AMBAL', objective: 'Compute BFA and AMBAL F-2 costs per $1M and compare with their category medians', depends_on: [], reads: ['knowledge'], tools: ['models.cost_on_assets', 'mstar.get_peers'], why: 'Dollar figures come only from the model platform.' }),
      L({ k: 'task', id: 'T2', agent: 'product.qar', title: 'Explain fit for Rachel’s plan', objective: 'Explain how BFA and AMBAL each fit Rachel’s retirement income plan, from approved material', depends_on: ['T1'], reads: ['memory', 'knowledge', 'policy'], tools: ['seismic.search_content'], why: 'QAR produces the verified answer.' }),
      L({ k: 'task', id: 'T3', agent: 'sales.schedule', title: 'Schedule meeting with Rachel', objective: 'Find a slot next month with Rachel and place a tentative hold', depends_on: [], reads: ['memory'], tools: ['calendar.find_times', 'calendar.create_event'], why: 'Schedule Me books meetings.' }),
      L({ k: 'decision', type: 'success', title: 'A comparison and a meeting on hold', detail: 'Verified costs, how each fund fits her plan, and a time waiting for Priya’s approval.' }),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.cost_on_assets', { tickers: ['BFA', 'AMBAL'], amount_usd: 1000000 }], ['mstar.get_peers', { category: 'BFA' }], ['mstar.get_peers', { category: 'AMBAL' }]],
        json: { says: 'Nearly identical cost, very different jobs. BFA F-2 is 0.34% and AMBAL F-2 is 0.35%, and both sit well under their category medians.',
          output: { kind: 'finding', title: 'BFA vs. AMBAL F-2: costs', body: '- BFA F-2 (ABNFX): 0.34%, about $3,400 a year per $1M; category median 0.46%\n- AMBAL F-2 (AMBFX): 0.35%, about $3,500 a year per $1M; category median 0.9%\n\nDifferent categories: BFA is a core bond fund; AMBAL holds stocks and bonds.' },
          used: ['ABNFX', 'AMBFX'], knowledge: [{ label: 'BFA and AMBAL F-2 cost per $1M', value: 'ABNFX 0.34% ($3,400 a year per $1M); AMBFX 0.35% ($3,500 per $1M). Category medians 0.46% and 0.9%.', evidence: ['models.cost_on_assets', 'mstar.get_peers', 'ABNFX', 'AMBFX'] }],
          memory: [], commitments: [], needs_approval: false, open_questions: [] } },
      T2: { calls: [['seismic.search_content', { query: 'balanced bond income retirement comparison' }]],
        json: { says: 'I framed it around what Rachel said she needs, reused Tool Selection’s numbers, and pointed to approved material instead of writing new claims.',
          output: { kind: 'answer', title: 'How each fits Rachel’s income plan', body: 'Rachel said her retirees want reliable income and she is reviewing balanced and bond funds (CALL-0923).\n\n- BFA: a core bond anchor for stability and income, managed against the Bloomberg U.S. Aggregate.\n- AMBAL: stocks and bonds in one fund, at least 50% stocks (mostly dividend payers) and at least 25% bonds, for growth plus income.\n\nApproved material: SEIS-123 compares the two roles; SEIS-121 and SEIS-122 cover each fund. Performance is inserted from the data platform at approval.' },
          used: ['MEM-061', 'CALL-0923', 'ABNFX', 'AMBFX', 'SEIS-121', 'SEIS-122', 'SEIS-123'], knowledge: [],
          memory: [{ attribute: 'Current priority', value: 'Reliable income for retirees; reviewing balanced and bond funds', scope: 'BU-106', category: 'priority', basis: 'advisor_statement', evidence: ['CALL-0923'] }], commitments: [], needs_approval: false, open_questions: [] } },
      T3: { calls: [['calendar.find_times', { attendees: ['ADV-106', 'Priya Shah'], when: 'next month' }], ['calendar.create_event', { title: 'BFA vs. AMBAL for your income plan', attendees: ['ADV-106', 'Priya Shah'], time: 'Tue Oct 6, 10:00 a.m. PT' }]],
        json: { says: 'Everyone is free on Tuesday, October 6 at 10:00 a.m. PT. I placed a tentative hold; the invite goes to Rachel once Priya approves it.',
          output: { kind: 'note', title: 'Meeting with Rachel', body: 'Tentative hold: Tue Oct 6, 10:00 a.m. PT (Rachel Okafor, Priya Shah).\nBackups: Wed Oct 14, 2:00 p.m.; Thu Oct 22, 11:00 a.m.\nThe invite goes to Rachel after Priya approves it.' },
          used: ['MEM-061'], knowledge: [], memory: [], commitments: [], needs_approval: true, open_questions: [] } }
    } }
);

/* Saved runs for the five demo-feedback requests. Authored to the demo script (not captured from a live
   model) and replayed through the same foundation, tools and gatekeeper, so every number must still trace. */
const D = (type, title, detail, extra) => L(Object.assign({ k: 'decision', type, title, detail }, extra || {}));
const TK = o => L(Object.assign({ k: 'task', depends_on: [], ask: 1 }, o));
RECORDED.push(
  { name: 'Prepare Maya’s retirement committee fee comparison review', requester: 'EMP-PRIYA', text: 'Prepare Maya’s retirement committee fee comparison review',
    orch: [
      D('requester', 'Priya Shah, Sales, covers Maya', 'Wholesaler on Maya Chen’s coverage; she owns the committee relationship and this review.'),
      D('intent', 'Committee review prep with numbers', 'Maya’s committee meets Nov 12 and wants a documented fee review. Priya needs the comparison and a plan.', { intent: 'meeting_prep' }),
      D('asks', '1 thing requested', 'Prepare the committee fee comparison review.', { asks: ['Prepare Maya’s committee fee comparison review'] }),
      D('entity', 'Maya → Maya Chen, retirement committee', '“Retirement committee” selects BU-102R, which oversees PLAN-102.', { advisor: 'ADV-102', unit: 'BU-102R', confidence: 'high' }),
      D('scope', 'Retirement committee only (BU-102R)', 'The wealth team (BU-102W) is out of scope; nothing from it shapes this review.'),
      D('known', 'Plan, lineup and committee asks on file', 'PLAN-102 lineup, Maya’s comparison basis and the committee’s concern; K-201 already explains active vs index.', { uses: ['PLAN-102', 'MEM-026', 'MEM-027', 'MEM-028', 'CALL-0919', 'K-201', 'TASK-302'] }),
      D('missing', 'No fee comparison computed yet', 'Category medians and dollar costs per option come from the model platform, never estimates.'),
      D('memory', 'Read only: basis already recorded', 'MEM-028 already holds how Maya wants fees compared. Nothing new to store.', { class: 'read_only' }),
      D('controls', 'Internal prep; committee pack later', 'No send. Numbers only from the platform and Morningstar; committee disclosures apply when it goes out.'),
      TK({ id: 'T1', agent: 'product.tools', role: 'product.analytics', title: 'Compute the plan fee comparison', objective: 'Compare each PLAN-102 option with its Morningstar category median in basis points and dollars, and cost both growth options on equal assets', reads: ['knowledge'], tools: ['models.plan_fee_comparison'], why: 'Investment analytics owns fee math; the model platform and Morningstar are the only sources for these numbers.' }),
      TK({ id: 'T2', agent: 'product.qar', role: 'product.specialists', title: 'Answer the committee’s two questions', objective: 'Answer why the active growth option (GFFFX) costs more than the index option (VIGAX), and what its benchmark represents (TASK-302), from verified evidence', depends_on: ['T1'], reads: ['memory', 'knowledge', 'policy'], tools: ['fund.get_facts', 'seismic.search_content'], why: 'Product specialists own verified answers; QAR reuses K-201 and checks the fund data platform and approved attribution in Seismic.' }),
      TK({ id: 'T3', agent: 'sales.prep', role: 'sales.wholesalers', title: 'Prepare Maya’s committee review brief', objective: 'Build Priya’s review brief: plan, lineup and fees, the committee’s objective and concerns, the answers, and what to send by when', depends_on: ['T1', 'T2'], reads: ['memory', 'knowledge', 'policy'], tools: ['crm.get_plan', 'crm.get_call_notes'], why: 'Prep Me builds Priya’s brief from the Salesforce plan record and Maya’s own words on recorded calls.' }),
      D('success', 'Priya walks Maya through every option', 'Each option against its category in dollars and basis points, both committee questions answered, a clear send plan.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.plan_fee_comparison', { plan_id: 'PLAN-102' }]],
        json: { says: 'I ran the plan’s lineup through the model platform against Morningstar category medians, the basis Maya asked for: every option with data sits below its median.',
          output: { kind: 'finding', title: 'PLAN-102 fee comparison vs category medians', body: 'Irvine Precision Manufacturing 401(k), $62M. Four options have expense data:\n\n- Large-cap growth, active (GFA F-2): 0.40% vs 0.75% median; $74,000 a year vs $138,750 at the median\n- Large-cap growth, index (VIGAX): 0.05% vs 0.75%; $4,500 vs $67,500\n- Balanced (AMBAL F-2): 0.35% vs 0.90%; $49,700 vs $127,800\n- Core bond (BFA F-2): 0.34% vs 0.46%; $23,120 vs $31,280\n\nWeighted cost of these four: 0.312%, $151,320 a year.\n\nThe committee’s question, on equal assets: on $18.5M the index option would cost $9,250 a year against GFA’s $74,000.\n\nNot covered: target-date and stable value ($13.5M), no expense data on file.' },
          used: ['PLAN-102', 'MEM-028'], knowledge: [{ label: 'PLAN-102 fee comparison against Morningstar category medians', value: 'All four options with expense data cost less than their category medians: GFA F-2 0.40% vs 0.75%, VIGAX 0.05% vs 0.75%, AMBAL F-2 0.35% vs 0.90%, BFA F-2 0.34% vs 0.46%. Weighted 0.312%.', evidence: ['models.plan_fee_comparison', 'PLAN-102'] }], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T2: { calls: [['fund.get_facts', { ticker: 'GFFFX' }], ['fund.get_facts', { ticker: 'VIGAX' }], ['seismic.search_content', { query: 'gfa attribution benchmark capital system' }]],
        json: { says: 'I reused Product’s earlier finding on why GFA trails the index, checked both funds on the data platform, and used Investment analytics’ dollar figures.',
          output: { kind: 'answer', title: 'Answers for Maya’s committee', body: '1. Why does the active growth option cost more than the index option?\nThey do different jobs. VIGAX tracks the CRSP US Large Cap Growth index, about 166 stocks. GFA is run by several independent managers (The Capital System), benchmarked to the S&P 500, with up to 25% outside the U.S. That research costs more: 0.40% vs 0.05%, or $74,000 vs $9,250 a year on the same $18.5M. Both sit below the 0.75% category median.\n\n2. What does the benchmark represent? (TASK-302)\nGFA is measured against the S&P 500, a broad large-cap index, not a growth index. Comparing it with a growth index measures style, not skill: when a few mega-cap growth stocks lead, the growth index leads (K-201).\n\nSources: GFFFX and VIGAX on the fund data platform; K-201; SEIS-113; SEIS-114.' },
          used: ['K-201', 'GFFFX', 'VIGAX', 'SEIS-113', 'SEIS-114', 'TASK-302', 'MEM-027'], knowledge: [{ label: 'Why an active growth fund costs more than a growth index option', value: 'Different jobs: VIGAX tracks a growth index; GFA uses several independent managers, the broader S&P 500 benchmark and some non-U.S. stocks. 0.40% vs 0.05%; both below the 0.75% Large Growth median.', evidence: ['GFFFX', 'VIGAX', 'K-201'] }], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T3: { calls: [['crm.get_plan', { advisor_id: 'ADV-102' }], ['crm.get_call_notes', { advisor_id: 'ADV-102' }]],
        json: { says: 'I built Priya’s brief from the plan record, Maya’s own words on her Sep 19 call, and the numbers and answers Product verified.',
          output: { kind: 'brief', title: 'Committee fee review: Maya Chen, PLAN-102', body: 'The plan: Irvine Precision Manufacturing 401(k), $62M, 540 participants. Committee meets Nov 12; materials to members Nov 5, and Maya reviews a draft first (EMAIL-0928).\n\nWhat the committee wants (CALL-0919):\n- A prudent fee review documented in the minutes\n- Each option against its Morningstar category median, in dollars and basis points\n- Why the active growth option costs more than the index option\n\nWhat we can now show (Investment analytics, Product specialists):\n- All four options with data are below their category medians; weighted 0.312%\n- Growth options on the same $18.5M: $74,000 active vs $9,250 index, explained by mandate and benchmark\n- The September benchmark question (TASK-302) is answered\n\nGap: no expense data for target-date and stable value ($13.5M).\n\nFormat: committee pack template (SEIS-116), sent by email (MEM-023).' },
          used: ['PLAN-102', 'CALL-0919', 'EMAIL-0928', 'MEM-023', 'MEM-026', 'MEM-027', 'MEM-028', 'TASK-302', 'SEIS-116', 'OPP-502'], knowledge: [], memory: [], commitments: [{ title: 'Send Maya the committee fee review draft in the committee pack format', owner: 'Priya Shah', due: 'Nov 2, 2026' }], needs_approval: false, open_questions: ['Which target-date series and stable value fund does the plan use? Needed to complete the comparison.'],
          next_step: 'Email Maya (her channel for committee prep) with the four-option comparison and both answers, and ask for the target-date and stable value fund names so the review covers the whole menu.' } }
    } },

  { name: 'Prep me for my call with Alex tomorrow (Sam)', requester: 'EMP-SAM', text: 'Prep me for my call with Alex tomorrow',
    orch: [
      D('requester', 'Sam Lee, Sales, taking over Alex', 'Sam becomes Alex Rivera’s primary coverage Oct 1 (HO-101). Priya’s notes carry over; her private coaching stays hers.'),
      D('intent', 'Handover call prep', 'Sam needs to walk in knowing what Priya already covered and what Alex decides at his Oct 1 committee.', { intent: 'meeting_prep' }),
      D('asks', '1 thing requested', 'Prep Sam for the call with Alex.', { asks: ['Prep Sam for the call with Alex'] }),
      D('entity', 'Alex → Alex Rivera, Morgan Stanley', 'One graph match; the growth-model unit holds the open decision and the last call.', { advisor: 'ADV-101', unit: 'BU-101A', confidence: 'high' }),
      D('scope', 'Growth model unit only (BU-101A)', 'The 401(k) committee unit is out of scope for this call.'),
      D('known', 'Reuse Priya’s calls and Product’s K-201', 'Priya recorded what Alex asked for (CALL-0922); Product already explained why GFA trailed. No re-research.', { uses: ['HO-101', 'CALL-0922', 'CALL-0814', 'K-201', 'MEM-011', 'MEM-017', 'MEM-014', 'TASK-301'] }),
      D('missing', 'Dollar costs on $38M not stored', 'Investment analytics computes them on the model platform; nobody estimates.'),
      D('memory', 'Read only: nothing new about Alex', 'A coverage change is workflow, not an advisor preference (POL-6). Memory is read, not changed.', { class: 'read_only' }),
      D('controls', 'Internal brief; coaching withheld', 'Priya’s private coaching (MEM-016) is not visible to Sam (POL-5). Every number traced.'),
      TK({ id: 'T1', agent: 'product.tools', role: 'product.analytics', title: 'Cost Alex’s $38M across three funds', objective: 'Compute annual costs on $38M for GFFFX, VWUAX and VIGAX', reads: ['knowledge'], tools: ['models.cost_on_assets'], why: 'Alex wants fees in dollars (MEM-017); only the model platform may produce them.' }),
      TK({ id: 'T2', agent: 'sales.schedule', role: 'sales.ssc', title: 'Check Alex’s call slot', objective: 'Check tomorrow against Alex’s meeting pattern and propose a slot through Jamie Cho', reads: ['memory'], tools: ['calendar.find_times'], why: 'SSC owns scheduling; Outlook shows Alex’s Tuesday and Thursday 7:30 a.m. pattern.' }),
      TK({ id: 'T3', agent: 'sales.prep', role: 'sales.wholesalers', title: 'Prepare Sam’s handover brief for Alex', objective: 'Build Sam’s one-page brief from Priya’s recorded calls, K-201 and T1’s dollar costs', depends_on: ['T1', 'T2'], reads: ['memory', 'knowledge', 'policy'], tools: ['crm.get_call_notes', 'crm.get_opportunities'], why: 'Prep Me builds Sam’s brief from Salesforce calls and opportunities, plus Product’s verified work.' }),
      D('success', 'Sam takes over; Alex repeats nothing', 'Dollar costs, Priya’s context, the Oct 1 decision and a clear first move for Sam.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.cost_on_assets', { tickers: ['GFFFX', 'VWUAX', 'VIGAX'], amount_usd: 38000000 }]],
        json: { says: 'I ran Alex’s $38M through the model platform: GFA F-2 costs $152,000 a year, VWUAX $95,000 and VIGAX $19,000.',
          output: { kind: 'finding', title: 'Costs on Alex’s $38M', body: '- GFA F-2 (GFFFX): 0.40%, $152,000 a year\n- Vanguard U.S. Growth (VWUAX): 0.25%, $95,000\n- Vanguard Growth Index (VIGAX): 0.05%, $19,000' },
          used: ['GFFFX', 'VWUAX', 'VIGAX', 'MEM-017'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T2: { calls: [['calendar.find_times', { advisor_id: 'ADV-101' }]],
        json: { says: '“Tomorrow” is Wednesday, outside Alex’s Tuesday and Thursday pattern, so I proposed Thursday at 7:30 a.m. PT through Jamie Cho, before his committee.',
          output: { kind: 'note', title: 'Call slot for Sam and Alex', body: 'Proposed: Thu Oct 1, 7:30 a.m. PT, Teams, before his committee.\nBackup: Tue Oct 6, 7:30 a.m. PT.\nBook through Jamie Cho (MEM-012).' },
          used: ['MEM-012'], knowledge: [], memory: [], commitments: [{ title: 'Ask Jamie Cho to book Thursday 7:30 a.m. for Alex and Sam', owner: 'Nina Alvarez', due: 'Sep 30' }], needs_approval: false, open_questions: [], next_step: '' } },
      T3: { calls: [['crm.get_call_notes', { advisor_id: 'ADV-101' }], ['crm.get_opportunities', { advisor_id: 'ADV-101' }]],
        json: { says: 'I built Sam’s brief from Priya’s recorded calls, Product’s finding on GFA and Investment analytics’ dollar costs, so Alex doesn’t have to repeat himself.',
          output: { kind: 'brief', title: 'Handover brief: Alex Rivera, for Sam', body: 'Why you’re calling: you become Alex’s primary coverage Oct 1 (HO-101). Priya stays on through his committee.\n\nWhat Priya already covered (CALL-0922, her call on Sep 22):\n- Alex asked for GFA vs the Vanguard growth funds, options for his growth sleeve, and why GFA has trailed\n- He wants one page, data first, no decks (MEM-011), and fees in dollars (MEM-017)\n\nThe decision: keep or replace GFA in his new growth model; committee Oct 1 (OPP-501, Proposal).\n\nLead with dollars on $38M:\n- GFA F-2 $152,000 a year; VWUAX $95,000; VIGAX $19,000\n\nWhy GFA trailed (K-201): different mandate and benchmark, mega-cap concentration in the index, and cost.\n\nStill owed: quarterly attribution in his one-page format (TASK-301), now yours.\n\nRapport (relationship note): training for the California International Marathon in December.' },
          used: ['HO-101', 'CALL-0922', 'K-201', 'MEM-011', 'MEM-017', 'MEM-014', 'MEM-015', 'TASK-301', 'OPP-501'], knowledge: [], memory: [], commitments: [{ title: 'Take over the quarterly attribution in Alex’s one-page format (TASK-301) from Priya', owner: 'Sam Lee', due: 'Jan 8, 2027' }], needs_approval: false, open_questions: ['Should Priya join Thursday’s call to make the introduction?'],
          next_step: 'Confirm Thursday 7:30 a.m. with Jamie Cho today, then open the call as Alex’s new primary coverage and walk him through the one-page dollar comparison before his committee.' } }
    } },

  { name: 'Why has GFA trailed the Vanguard growth index?', requester: 'EMP-DANA', text: 'Why has GFA trailed the Vanguard growth index? I need an explanation advisors can use.',
    orch: [
      D('requester', 'Dana Ortiz, Product specialist', 'Owns product answers for the field; no advisor relationship data is needed.'),
      D('intent', 'Verified explanation for advisors', 'A product question with an advisor-facing deliverable.', { intent: 'research' }),
      D('asks', '2 things requested', '1. Explain why GFA trailed · 2. Make it usable by advisors', { asks: ['Explain why GFA trailed the growth index', 'Make it usable by advisors'] }),
      D('entity', 'No advisor; GFFFX and VIGAX', 'GFA resolves to GFFFX (F-2); the Vanguard growth index to VIGAX.', { advisor: null, unit: null, territory: null, confidence: 'high' }),
      D('scope', 'Product level, reusable by anyone', 'No client data. The answer is published for Sales and Marketing to reuse.'),
      D('known', 'K-201 and the attribution report exist', 'K-201 explains the gap; SEIS-113 is the approved attribution report. Refresh, don’t redo.', { uses: ['K-201', 'SEIS-113', 'SEIS-114', 'GFFFX', 'VIGAX'] }),
      D('missing', 'Cost gap in dollars not stored', 'Investment analytics computes it per $1M on the platform. Returns are never generated (POL-3).'),
      D('memory', 'None: no advisor involved', 'Nothing about an advisor is read or stored.', { class: 'none' }),
      D('controls', 'Approved language for the advisor version', 'Advisor-ready text uses approved messaging (MSG- ids); performance inserted only at approval.'),
      TK({ id: 'T1', agent: 'product.tools', role: 'product.analytics', title: 'Quantify cost and peer context', objective: 'Compute the cost gap between GFFFX and VIGAX per $1M and pull the Large Growth category median', reads: ['knowledge'], tools: ['models.cost_on_assets', 'mstar.get_peers'], why: 'Investment analytics runs fee math on the model platform and peer data from Morningstar.' }),
      TK({ id: 'T2', agent: 'product.qar', role: 'product.specialists', title: 'Verify why GFA trailed', objective: 'Refresh K-201 into a verified explanation of mandate, concentration and cost, citing GFFFX, VIGAX and SEIS-113', depends_on: ['T1'], reads: ['knowledge', 'policy'], tools: ['fund.get_facts', 'seismic.search_content', 'fund.get_performance'], why: 'QAR publishes verified findings; it checks the fund data platform and the approved attribution report in Seismic.' }),
      TK({ id: 'T3', agent: 'product.tone', role: 'product.specialists', ask: 2, title: 'Write advisor-ready talking points', objective: 'Turn the verified explanation into talking points advisors can use, in approved messaging', depends_on: ['T2'], reads: ['knowledge', 'policy'], tools: ['seismic.get_approved_language'], why: 'Tone/Style Alignment owns advisor-facing language; it pulls approved messaging from Seismic so nothing new is claimed.' }),
      D('success', 'Advisors can explain it in a minute', 'A verified internal finding, then talking points in approved language, each with sources.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['models.cost_on_assets', { tickers: ['GFFFX', 'VIGAX'], amount_usd: 1000000 }], ['mstar.get_peers', { category: 'Large Growth' }]],
        json: { says: 'Per $1 million, GFA F-2 costs $4,000 a year and VIGAX $500; the Morningstar Large Growth median is 0.75%, so both sit below it.',
          output: { kind: 'finding', title: 'Cost and peer context: GFA vs VIGAX', body: '- GFA F-2 (GFFFX): 0.40%, $4,000 a year per $1M\n- Vanguard Growth Index (VIGAX): 0.05%, $500 per $1M\n- Large Growth median: 0.75% (Morningstar)\n\nCost explains 0.35 points a year of any gap, before mandate differences.' },
          used: ['GFFFX', 'VIGAX', 'K-201'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T2: { calls: [['fund.get_facts', { ticker: 'GFFFX' }], ['fund.get_facts', { ticker: 'VIGAX' }], ['seismic.search_content', { query: 'gfa attribution why trailed' }], ['fund.get_performance', { ticker: 'GFFFX' }]],
        json: { says: 'I refreshed Product’s K-201 against the data platform and the approved attribution report, and folded in Investment analytics’ cost figures.',
          output: { kind: 'finding', title: 'Why GFA has trailed the Vanguard growth index (verified)', body: '- Different job: GFA is benchmarked to the S&P 500 and invests flexibly across 282 issuers, with up to 25% outside the U.S. (10.8% non-U.S. equities). VIGAX tracks the CRSP US Large Cap Growth index.\n- Concentration: the index holds about 166 stocks, with the top three roughly a third of assets. When a few mega-cap growth stocks lead, it leads.\n- Cost: 0.40% vs 0.05%, $4,000 vs $500 a year per $1M.\n\nNot a skill verdict: judge GFA against the S&P 500 it is managed to.\n\nPerformance: standardized returns are inserted from the fund data platform at approval; SEIS-113 has the quarter’s attribution.' },
          used: ['K-201', 'GFFFX', 'VIGAX', 'SEIS-113'], knowledge: [{ label: 'Why GFA has trailed the Vanguard growth index (refreshed)', value: 'Different mandates: GFA is benchmarked to the S&P 500 across 282 issuers with up to 25% outside the U.S.; the growth index holds about 166 stocks with roughly a third in three, so it leads when mega-caps lead; GFA F-2 costs 0.40% vs 0.05% for VIGAX.', evidence: ['GFFFX', 'VIGAX', 'SEIS-113', 'K-201'] }], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T3: { calls: [['seismic.get_approved_language', { topic: 'active index performance benchmark' }]],
        json: { says: 'I turned Product specialists’ verified finding into talking points built on approved messaging, so advisors can use them without new claims.',
          output: { kind: 'answer', title: 'Talking points: why GFA has trailed the growth index', body: 'For advisors, in approved language:\n\n- “Active and index funds do different jobs. An index fund aims to match its benchmark; an active fund aims to do something different, so it will lead and lag at different times.” (MSG-211)\n- GFA is managed to the S&P 500, not a growth index. When a handful of mega-cap growth stocks drive the market, a growth index with about a third of its assets in three stocks will lead.\n- “The Capital System divides each portfolio among several managers who invest independently, so no single view dominates.” (MSG-212)\n- “Judge a fund over a full market cycle and against the benchmark it is managed to, not a single period or a different index.” (MSG-213)\n- Cost is part of it: 0.40% for GFA F-2 vs 0.05% for VIGAX.\n\nUse with SEIS-113 (attribution) and SEIS-114 (Capital System explainer). Returns are added from the data platform at approval.' },
          used: ['MSG-211', 'MSG-212', 'MSG-213', 'K-201', 'SEIS-113', 'SEIS-114'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [],
          next_step: 'Share the talking points with the Wholesalers alongside SEIS-113 and SEIS-114, so every advisor conversation uses the same verified explanation.' } }
    } },

  { name: 'Write a LinkedIn post on fee transparency for advisors', requester: 'EMP-MARCUS', text: 'Write a LinkedIn post on fee transparency for advisors',
    orch: [
      D('requester', 'Marcus Bell, Marketing', 'Advisor marketing lead; may draft public posts. No advisor or client data is needed.'),
      D('intent', 'One public LinkedIn post', 'Educational post for financial professionals, published from the company page.', { intent: 'content' }),
      D('asks', '1 thing requested', 'Write the LinkedIn post.', { asks: ['Write a LinkedIn post on fee transparency'] }),
      D('entity', 'No advisor: public content', 'Audience is financial professionals on LinkedIn. No advisor, firm or client may be named (POL-8).', { advisor: null, unit: null, territory: null, confidence: 'high' }),
      D('scope', 'Public and product level only', 'Nothing from advisor memory, notes or cases goes into a public post.'),
      D('known', 'Approved template and messaging exist', 'SEIS-118 is the approved LinkedIn template; Seismic holds approved fee messaging.', { uses: ['SEIS-118', 'SEIS-115', 'POL-8'] }),
      D('missing', 'What advisors actually ask about fees', 'Service sees the real questions; Marketing Cloud knows which fee content landed. Pull both before drafting.'),
      D('memory', 'None: no advisor involved', 'Nothing about an advisor is read or stored.', { class: 'none' }),
      D('controls', 'Draft, compliance review, approval', 'Approved messaging only, social disclosures in the post, nothing published without Marcus’s approval.'),
      TK({ id: 'T1', agent: 'marketing.gather', role: 'marketing.content', title: 'Gather approved fee inputs', objective: 'Pull the approved LinkedIn template, approved fee messaging, the page to link to, and how past fee content performed', reads: ['knowledge', 'policy'], tools: ['seismic.search_content', 'seismic.get_approved_language', 'aem.get_page', 'mcloud.get_engagement'], why: 'Resource Gatherer finds approved content in Seismic, the published page in Adobe Experience Manager and past results in Marketing Cloud.' }),
      TK({ id: 'T2', agent: 'marketing.voc', role: 'marketing.content', title: 'Find advisors’ real fee questions', objective: 'Pull what advisors asked Service about fees this quarter, without identifiers', reads: ['policy'], tools: ['service.get_insights'], why: 'Voice of Client brings in Service’s Genesys and case data, so the post answers real questions.' }),
      TK({ id: 'T3', agent: 'marketing.linkedin', role: 'marketing.content', title: 'Draft the LinkedIn post', objective: 'Draft one post that answers advisors’ top fee question in approved language and links to the approved page', depends_on: ['T1', 'T2'], reads: ['knowledge', 'policy'], tools: [], why: 'LinkedIn Post drafts public posts with no identifiers.' }),
      TK({ id: 'T4', agent: 'marketing.legal', role: 'marketing.compliance', title: 'Review the post for social rules', objective: 'Check claims against approved messaging and apply the social disclosures and channel rules', depends_on: ['T3'], reads: ['policy'], tools: ['sharepoint.get_disclosures'], why: 'Legal & Compliance pulls the social-channel rules from the SharePoint compliance library.' }),
      D('success', 'A post advisors would share', 'Answers the question advisors actually ask, in approved language, compliant and waiting for approval.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['seismic.search_content', { query: 'linkedin fees transparency' }], ['seismic.get_approved_language', { topic: 'fees' }], ['aem.get_page', { query: 'fees expenses' }], ['mcloud.get_engagement', { topic: 'fees' }]],
        json: { says: 'I pulled the approved template and fee messaging from Seismic, the published fees page from Adobe Experience Manager, and Marketing Cloud results: dollar framing wins.',
          output: { kind: 'content_pick', title: 'Approved inputs for the fee post', body: '- Template: SEIS-118, LinkedIn post template for fee education\n- Approved messaging: MSG-201 (costs in dollars and percentages), MSG-203 (expense ratio, share class, as-of date), MSG-202 (what you get for the fee)\n- Link: AEM-FEES “Understanding fund expenses”, published, reviewed Aug 2026\n- What landed before (Marketing Cloud): fee posts that showed the cost in dollars engaged at 3.8% against a 1.6% average' },
          used: ['SEIS-118', 'MSG-201', 'MSG-202', 'MSG-203', 'AEM-FEES'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T2: { calls: [['service.get_insights', { topic: 'fees' }]],
        json: { says: 'I pulled what advisors asked Service about fees this quarter from Genesys and Service Cloud: how to explain fees, not whether they are too high.',
          output: { kind: 'finding', title: 'What advisors ask Service about fees (Q3)', body: '- Fee contacts: 46 this quarter, up from 27\n- Top question: how to show a client what a fee costs in dollars, not just percent\n- Also: why a statement’s expense ratio differs from the fact sheet (share class), and F-2 vs Class A costs\n\nTakeaway: advisors want help explaining fees, not reassurance that fees are low.' },
          used: [], knowledge: [{ label: 'Advisors’ top fee questions this quarter', value: 'Fee contacts rose to 46 from 27. Advisors most often ask how to show a client what a fee costs in dollars, and why statement expense ratios differ by share class.', evidence: ['service.get_insights'] }], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T3: { calls: [],
        json: { says: 'I answered the fee question advisors ask Service most, using approved messaging and the dollar framing that has performed best.',
          output: { kind: 'post', title: 'LinkedIn: what a fee costs, in dollars', body: 'Your clients rarely ask “Is this expense ratio high?” They ask “What does it cost me?”\n\nCosts matter. We show what each share class costs, in dollars as well as percentages, so there are no surprises.\n\nThree things belong in any fee conversation:\n- The expense ratio\n- The share class\n- The as-of date\n\nA lower fee is one input. What you get for the fee (the approach, the people, the long-term results) is the rest of the story.\n\nHow to read fund expenses, in plain terms: Understanding fund expenses [link]' },
          used: ['MSG-201', 'MSG-202', 'MSG-203', 'SEIS-118', 'AEM-FEES'], knowledge: [], memory: [], commitments: [], needs_approval: true, open_questions: [], next_step: '' } },
      T4: { calls: [['sharepoint.get_disclosures', { content_type: 'LinkedIn post' }]],
        json: { says: 'Claims match approved messaging and nothing identifies an advisor; the post still needs the three social disclosures before Marcus approves it.',
          output: { kind: 'note', title: 'Compliance review: fee transparency post', body: 'Checked against the social-channel rules (SharePoint compliance library):\n- Claims: all from approved messaging (MSG-201, MSG-202, MSG-203). Pass\n- Names: no advisor, firm or client (POL-8). Pass\n- Performance, rankings or forecasts: none. Pass\n- Link: AEM-FEES is published and approved. Pass\n- Disclosures: missing. Add them to the post itself, not a comment:\n“Investing involves risk, including loss of principal. Expense ratios are as of each fund’s current prospectus. Educational content, not investment advice.”\n\nResult: approve once the disclosures are in.' },
          used: ['POL-8', 'MSG-201', 'MSG-202', 'MSG-203', 'AEM-FEES'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [],
          next_step: 'Click Edit on the post, add the three disclosures at the end, re-check and approve.' } }
    } },

  { name: 'Alex says the link in Priya’s email won’t open', requester: 'EMP-KIM', text: 'Alex says the link in Priya’s email won’t open',
    orch: [
      D('requester', 'Kim Nguyen, Advisor service', 'Owns access and delivery cases; sees cases, contacts and delivery logs, not relationship notes.'),
      D('intent', 'Access problem on a sent email', 'Alex can’t open content Priya sent. Diagnose and fix before his Thursday committee.', { intent: 'service' }),
      D('asks', '1 thing requested', 'Fix the link Alex can’t open.', { asks: ['Fix the link Alex can’t open'] }),
      D('entity', 'Alex → Alex Rivera; Priya is a colleague', 'Alex Rivera at Morgan Stanley. Priya Shah is the Capital Group sender, not an advisor.', { advisor: 'ADV-101', unit: null, confidence: 'high' }),
      D('scope', 'Alex’s account and Priya’s Sep 28 send', 'Case CASE-00517, Jamie’s call INT-7731 and the LiveSend link LS-0928.'),
      D('known', 'An open case and a precedent', 'CASE-00517 is open from Jamie’s call; CASE-00481 resolved the same symptom in July.', { uses: ['CASE-00517', 'CASE-00481', 'INT-7731', 'MEM-013'] }),
      D('missing', 'Root cause not confirmed yet', 'Check the delivery log before assuming: expired link, recipient access, or the firm’s gateway.'),
      D('memory', 'Read only: the rule is already known', 'MEM-013 already records that Morgan Stanley blocks external links. Nothing new to store.', { class: 'read_only' }),
      D('controls', 'Same approved version, no new content', 'Resend the identical approved asset as a PDF; Kim sends it from the case.'),
      TK({ id: 'T1', agent: 'service.classify', role: 'service.advisor', title: 'Classify and pull the contact', objective: 'Classify the inquiry from Jamie’s call and match it to the open case', reads: ['memory', 'policy'], tools: ['contact.get_interactions', 'service.get_cases'], why: 'Inquiry Classifier reads the call in Genesys Cloud and the cases in Service Cloud.' }),
      TK({ id: 'T2', agent: 'service.resolve', role: 'service.advisor', title: 'Diagnose and resolve the link', objective: 'Confirm the root cause from the LiveSend delivery log, rule out the other causes, export the same approved one-pager as a PDF and update CASE-00517', depends_on: ['T1'], reads: ['memory', 'policy'], tools: ['seismic.get_delivery_log', 'seismic.export_pdf', 'service.update_case'], why: 'Resolve Me owns access fixes; the Seismic delivery log shows what happened to every click.' }),
      D('success', 'Alex has the one-pager before Thursday', 'Root cause shown with evidence, the same approved PDF ready, the case updated and Priya informed.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['contact.get_interactions', { advisor_id: 'ADV-101' }], ['service.get_cases', { advisor_id: 'ADV-101' }]],
        json: { says: 'I matched Jamie Cho’s call this morning to open case CASE-00517 and classified it as access and delivery; it looks like July’s CASE-00481.',
          output: { kind: 'note', title: 'Classification: access and delivery', body: 'Jamie Cho called the service line this morning (INT-7731). Alex tried the link in Priya’s Sep 28 email three times from the office and saw “This site is blocked by your organization’s security policy.” It opened on his personal phone.\n\nThat matches open case CASE-00517. Category: access and delivery. Priority: high, because his committee meets Thursday.\n\nWe resolved the same symptom in July (CASE-00481): the firm’s web gateway blocks external file-sharing links.' },
          used: ['INT-7731', 'CASE-00517', 'CASE-00481', 'MEM-013'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], next_step: '' } },
      T2: { calls: [['seismic.get_delivery_log', { advisor_id: 'ADV-101' }], ['seismic.export_pdf', { asset_id: 'SEIS-110' }], ['service.update_case', { case_id: 'CASE-00517', status: 'Pending advisor', note: 'Root cause: the Morgan Stanley web gateway blocks external file-sharing links; every office click on LS-0928 stopped there. Link active and recipients permitted. Same approved SEIS-110 exported as a PDF for Jamie Cho.' }]],
        json: { says: 'The delivery log shows the firm’s gateway stopping every office click, so I exported the same approved one-pager as a PDF and updated the case.',
          output: { kind: 'case_update', title: 'CASE-00517: link blocked by the firm’s web gateway', body: 'Jamie Cho called this morning for Alex: the link in Priya’s Sep 28 email to the fund comparison one-pager won’t open from his office.\n\nI checked the three usual causes in the Seismic delivery log (LS-0928). The link hasn’t expired; it stays active until Oct 28. Alex and Jamie are both on the recipient list, so it isn’t permissions. Every click from the Morgan Stanley network was stopped at the firm’s web gateway as file sharing, while the open from his phone worked. That’s the cause we resolved in July (CASE-00481), and it matches the firm rule on file (MEM-013).\n\nI exported the same approved one-pager as a PDF (SEIS-110, unchanged) and moved the case to Pending advisor. Next, the PDF goes to Jamie as an attachment; I’ll close the case once Alex confirms it opens.' },
          used: ['LS-0928', 'CASE-00517', 'CASE-00481', 'MEM-013', 'SEIS-110', 'INT-7731'], knowledge: [], memory: [], commitments: [{ title: 'Send Jamie Cho the SEIS-110 PDF and confirm it opens for Alex', owner: 'Kim Nguyen', due: 'Sep 29' }], needs_approval: false, open_questions: [],
          next_step: 'Send the PDF to Jamie Cho from CASE-00517 today, and tell Priya that future sends to Morgan Stanley should go as attachments, not links.' } }
    } }
);

/* Saved runs for the Sales AI intelligence and orchestration layer (authored to the query catalogue,
   replayed through the same foundation, tools and gatekeeper). Each starts with a structured
   interpretation and plans in waves; steps in a wave run together. */
const NOTES_DANIEL = { kind: 'note', title: 'What Daniel told us', body: '- Aug 26 (CALL-0826, Sam Lee’s call): Daniel moved two client models to a core-satellite structure with an index core, and reviews the satellite funds every quarter.\n- Sep 18 (CALL-0918, Priya’s call): “Clients keep asking about ETFs versus active funds.” He wants model portfolio options with a lower blended cost.\n\nStated priority (MEM-051): lower-cost model portfolios with a core-satellite structure.' };
RECORDED.push(
  { name: 'Why are Daniel’s overall sales down when his ETF sales are up?', requester: 'EMP-PRIYA', text: 'Why are Daniel’s overall sales down when his ETF sales are up?',
    orch: [
      D('requester', 'Priya Shah, Sales, covers Daniel', 'Wholesaler on Daniel Kim’s coverage; she owns the relationship.'),
      D('intent', 'Diagnose a change, not find leads', 'She wants the reason total sales fell while ETF sales grew, not an ETF pitch or a lead list.', { intent: 'diagnose' }),
      D('asks', '1 thing requested', 'Explain why sales are down while ETF sales are up.', { asks: ['Explain sales down, ETF sales up'] }),
      D('interpretation', 'Explain why Daniel’s total CG sales fell while his ETF sales grew', 'Catalogue #10 with #11 and #16.', { subject: { kind: 'advisor', id: 'ADV-105', label: 'Daniel Kim · The Kim Group' }, intent: 'diagnose', scope: 'Kim Group team, Capital Group book, all vehicles (mutual funds, ETFs, SMAs) and both channels', time: 'Trailing twelve months to Aug 2026 against the twelve months before', constraints: ['Numbers only from the flows service', 'Separate percentage growth from dollar contribution'], output: 'comparison', missing: ['Fund-level transactions are not connected, so the explanation stops at vehicle and channel'], authority: 'read_only', patterns: [10, 11, 16] }),
      D('entity', 'Daniel → Daniel Kim, Wells Fargo', 'One graph match; his only unit is the Kim Group model portfolios.', { advisor: 'ADV-105', unit: 'BU-105', confidence: 'high' }),
      D('scope', 'Kim Group model portfolios (BU-105)', 'Team-level CG book; no other managers’ flows.'),
      D('known', 'Daniel’s own words may explain it', 'CALL-0826: two models moved to an index core. CALL-0918: clients ask about ETFs versus active.', { uses: ['CALL-0826', 'CALL-0918', 'MEM-051', 'MEM-053'] }),
      D('missing', 'Flows not computed yet', 'The flows service computes the contribution by vehicle and channel; the model only explains it.'),
      D('memory', 'Read only', 'Nothing new about Daniel to store.', { class: 'read_only' }),
      D('controls', 'Read-only; every number traced', 'No drafts or changes. Figures only from the flows service.'),
      TK({ id: 'T1', route: 'Lead.Insights', title: 'Compute the contribution analysis', objective: 'Compare gross sales, redemptions and net flows by vehicle and channel for both periods, and attribute the change in total sales', services: ['flows'], tools: ['book.get_flows'], reads: ['knowledge'], returns: 'Contribution by vehicle and channel, with the periods and limits', why: 'Lead Me’s Insights Generator explains changes; the flows service on the data platform does the math.' }),
      TK({ id: 'T2', route: 'Prep.Notes', title: 'Pull what Daniel told us', objective: 'Summarize Daniel’s dated statements about his models, ETFs and the index core', services: ['memory'], tools: ['crm.get_call_notes'], reads: ['memory'], returns: 'Attributed statements with dates', why: 'Notes Summarizer reads recorded calls in Salesforce; it runs alongside the flows analysis.' }),
      TK({ id: 'T3', route: 'Prep.Fact Check', title: 'Check and explain the gap', objective: 'Verify every figure against the flows result, reconcile it with Daniel’s statements and state the limits', depends_on: ['T1', 'T2'], reads: ['memory', 'knowledge', 'policy'], tools: [], returns: 'A verified explanation with sources, as-of dates and limits', why: 'Fact Check makes sure the explanation uses the flows numbers, not narrative.' }),
      D('success', 'Priya can explain the dip in one breath', 'Dollar contribution by vehicle and channel, tied to what Daniel said, with the limits stated.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['book.get_flows', { advisor_id: 'ADV-105' }]],
        json: { says: 'I ran the flows service for both periods: ETF sales more than doubled, but the mutual fund decline is nearly twice as large in dollars.',
          output: { kind: 'finding', title: 'Contribution analysis: Kim Group sales', body: 'Total gross sales: $38.2M vs $44.9M, down $6.7M (−14.9%).\n\nBy vehicle (change in gross sales):\n- Mutual funds: $21.4M vs $33.1M, down $11.7M\n- ETFs: $11.6M vs $5.2M, up $6.4M (+123.1%)\n- SMAs: $5.2M vs $6.6M, down $1.4M\n\nBy channel: model portfolios $24.0M vs $33.5M (down $9.5M); advisor-directed accounts $14.2M vs $11.4M (up $2.8M).\n\nRedemptions rose to $23.0M from $15.8M, mostly mutual funds ($18.9M vs $12.4M), so net flows fell to $15.2M from $29.1M.' },
          used: ['book.get_flows'], knowledge: [{ label: 'Kim Group sales: mutual fund decline outweighs ETF growth', value: 'Gross sales fell $6.7M (−14.9%): mutual fund sales fell $11.7M while ETF sales rose $6.4M; model-portfolio channel sales fell $9.5M.', evidence: ['book.get_flows'] }], memory: [], commitments: [], needs_approval: false,
          open_questions: ['Fund-level transactions are not connected, so the decline can’t be traced to specific funds.'], as_of: ['Sep 2025 to Aug 2026'], status: 'complete', next_step: '' } },
      T2: { calls: [['crm.get_call_notes', { advisor_id: 'ADV-105' }]],
        json: { says: 'I pulled Daniel’s own words from Sam’s August call and Priya’s September call; both point at his models.',
          output: NOTES_DANIEL, used: ['CALL-0826', 'CALL-0918', 'MEM-051', 'MEM-053'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: ['Sep 18, 2026'], status: 'complete', next_step: '' } },
      T3: { calls: [],
        json: { says: 'I checked every figure against the flows result and tied it to what Daniel told Sam and Priya; the explanation stops where the data stops.',
          output: { kind: 'answer', title: 'Why sales are down while ETF sales are up', body: 'Short answer: ETF sales grew fast from a small base, while mutual fund sales fell by more.\n\n- ETFs: up $6.4M (+123.1%), the only vehicle that grew\n- Mutual funds: down $11.7M, which outweighs the ETF gain on its own\n- Net effect: total gross sales down $6.7M (−14.9%)\n\nWhere it happened: the model-portfolio channel fell $9.5M while advisor-directed accounts rose $2.8M. That matches what Daniel told us: two models moved to an index core (CALL-0826) and he wants a lower blended cost (CALL-0918).\n\nLimits: fund-level transactions are not connected, so this can’t say which funds the models replaced.' },
          used: ['book.get_flows', 'CALL-0826', 'CALL-0918', 'MEM-051'], knowledge: [], memory: [], commitments: [], needs_approval: false,
          open_questions: ['Which funds did the two index-core models replace? Needs fund-level transactions (not connected).'], as_of: ['Sep 2025 to Aug 2026', 'Sep 18, 2026'], status: 'complete',
          next_step: 'Lead with the model-portfolio shift, not the ETF growth: ask Daniel which satellite funds he is reviewing this quarter, since that is where mutual fund sales fell.' } }
    } },

  { name: 'Which CG ETFs are available at Wells Fargo for Daniel?', requester: 'EMP-PRIYA', text: 'Which CG ETFs are available at Wells Fargo for Daniel?',
    orch: [
      D('requester', 'Priya Shah, Sales, covers Daniel', 'Wholesaler on Daniel Kim’s coverage.'),
      D('intent', 'Verify availability on his platform', 'Not “find ETF leads” or “prepare an ETF discussion”: a scoped availability check.', { intent: 'verify' }),
      D('asks', '1 thing requested', 'Which CG ETFs Daniel can use at Wells Fargo.', { asks: ['Which CG ETFs are available for Daniel'] }),
      D('interpretation', 'Verify which CG ETFs Daniel can use on his own Wells Fargo programs, today', 'Catalogue #25 with #26 and #32.', { subject: { kind: 'advisor', id: 'ADV-105', label: 'Daniel Kim · Wells Fargo Advisors' }, intent: 'verify', scope: 'Wells Fargo Advisors; Daniel’s own programs, not dealer-wide; vehicle: ETF', time: 'Current, with effective dates from the dealer feed', constraints: ['Platform availability is not suitability', '“CG ETFs” resolved by the taxonomy, not keyword matching'], output: 'answer', missing: [], authority: 'read_only', patterns: [25, 26, 32] }),
      D('entity', 'Daniel → Daniel Kim, Wells Fargo', 'One graph match.', { advisor: 'ADV-105', unit: 'BU-105', confidence: 'high' }),
      D('scope', 'His programs, ETF vehicle only', 'Dealer-wide availability, his programs and client suitability are kept separate.'),
      D('known', 'Firm known; programs not yet', 'The graph says Wells Fargo; which programs he uses comes from CRM.', { uses: ['ADV-105'] }),
      D('missing', 'Which programs Daniel uses', 'Prep.Profile reads it from CRM first, so the platform check is scoped to his programs.'),
      D('memory', 'Read only', 'Nothing new to store.', { class: 'read_only' }),
      D('controls', 'Read-only; no suitability claims', 'Availability only, with effective dates and source.'),
      TK({ id: 'T1', route: 'Prep.Profile', title: 'Confirm Daniel’s programs', objective: 'Read Daniel’s firm and the platform programs he uses from CRM', tools: ['crm.get_contact'], reads: ['memory'], returns: 'Firm and programs', why: 'Profile reads the advisor’s account context from Salesforce.' }),
      TK({ id: 'T2', route: 'Product.Research Planner', title: 'Pull the Wells Fargo ETF shelf', objective: 'Resolve “CG ETFs” to tickers and pull program-level availability with effective dates for Daniel’s programs', depends_on: ['T1'], services: ['platform eligibility', 'taxonomy'], tools: ['platform.get_availability', 'taxonomy.resolve'], reads: ['knowledge'], returns: 'Program-level availability for every CG ETF, with effective dates', why: 'Research Planner decides the evidence; the taxonomy and platform eligibility services supply it.' }),
      TK({ id: 'T3', route: 'Product.QAR', title: 'Verify his scoped availability', objective: 'Combine his programs with the shelf into a verified, scoped answer with sources', depends_on: ['T1', 'T2'], reads: ['knowledge', 'policy'], tools: [], returns: 'Scoped list with status, effective dates and source', why: 'QAR publishes verified answers only.' }),
      D('success', 'One scoped answer, no overreach', 'What he can use in each of his programs, as of the feed date, with what is pending.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['crm.get_contact', { advisor_id: 'ADV-105' }]],
        json: { says: 'I read Daniel’s account context from CRM: he runs his models in Personalized UMA and also uses Brokerage.',
          output: { kind: 'note', title: 'Daniel’s programs', body: 'Daniel Kim, Managing Director, Wells Fargo Advisors (Century City).\n\nPrograms he uses: Personalized UMA (his model portfolios) and Brokerage.' }, used: ['ADV-105'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: [], status: 'complete', next_step: '' } },
      T2: { calls: [['taxonomy.resolve', { term: 'etfs' }], ['platform.get_availability', { advisor_id: 'ADV-105' }]],
        json: { says: 'With Profile’s programs in hand, I resolved “CG ETFs” through the taxonomy and pulled each one’s status by program from the dealer feed.',
          output: { kind: 'finding', title: 'Wells Fargo shelf: Capital Group ETFs', body: 'Taxonomy “ETFs”: CGGR, CGDV, CGCP, CGUI, CGXU.\n\nWells Fargo Advisors, as of Sep 28, 2026 (dealer intelligence feed):\n- CGGR: Brokerage available; Personalized UMA available from Sep 22, 2026\n- CGDV: Brokerage and Personalized UMA available\n- CGCP: Brokerage available; Personalized UMA under review\n- CGUI: Brokerage available; not available in Personalized UMA\n- CGXU: Brokerage available; not available in Personalized UMA' },
          used: ['taxonomy.resolve', 'platform.get_availability'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: ['Sep 28, 2026'], status: 'complete', next_step: '' } },
      T3: { calls: [],
        json: { says: 'I combined Daniel’s programs with the shelf: two ETFs fit his UMA models today, one is under review.',
          output: { kind: 'answer', title: 'CG ETFs Daniel can use at Wells Fargo', body: 'For his Personalized UMA models:\n- Available: CGDV, and CGGR (added Sep 22, 2026, after your last call on Sep 18)\n- Under review: CGCP\n- Not available: CGUI, CGXU\n\nIn Brokerage accounts: all five are available.\n\nScope: platform availability for Daniel’s programs, not a suitability conclusion for any client. Expense ratios for these ETFs are not in the reference data, so none are quoted.' },
          used: ['platform.get_availability', 'taxonomy.resolve', 'ADV-105', 'CALL-0918'], knowledge: [], memory: [], commitments: [], needs_approval: false,
          open_questions: ['When will Wells Fargo finish reviewing CGCP for Personalized UMA?'], as_of: ['Sep 28, 2026'], status: 'complete',
          next_step: 'Tell Daniel that CGGR is newly available in his Personalized UMA models, and check the CGCP review before suggesting it there.' } }
    } },

  { name: 'Prepare me for tomorrow’s meeting with Daniel’s team', requester: 'EMP-PRIYA', text: 'Prepare me for tomorrow’s meeting with Daniel’s team',
    orch: [
      D('requester', 'Priya Shah, Sales, covers Daniel', 'Wholesaler on Daniel Kim’s coverage.'),
      D('intent', 'Prepare a meeting: a brief, not actions', '“Prepare me” means the brief and agenda. It does not book, send or update anything.', { intent: 'prepare' }),
      D('asks', '1 thing requested', 'Prepare the meeting with Daniel’s team.', { asks: ['Prepare the meeting with Daniel’s team'] }),
      D('interpretation', 'Build a meeting-specific brief and agenda for tomorrow with the Kim Group', 'Catalogue #1 with #3 and #33.', { subject: { kind: 'buying_unit', id: 'BU-105', label: 'Daniel Kim · Kim Group model portfolios' }, intent: 'prepare', scope: 'Wealth: Kim Group model portfolios at Wells Fargo Advisors', time: 'Meeting tomorrow (Wed Sep 30); changes since the last meeting on Sep 18', constraints: ['Return the agenda, not an email or CRM update', 'Approved content only'], output: 'agenda', missing: ['Meeting length and purpose are not on the calendar; assuming 30 minutes on the model refresh'], authority: 'read_only', patterns: [1, 3, 33] }),
      D('entity', 'Daniel → Daniel Kim, Kim Group', 'One graph match; the model-portfolio unit is the only unit.', { advisor: 'ADV-105', unit: 'BU-105', confidence: 'high' }),
      D('scope', 'Model portfolios unit (BU-105)', 'Everything in the brief is about this unit.'),
      D('known', 'Recent calls, priorities, open opportunity', 'Two recorded calls, a stated priority and OPP-504 in Discovery.', { uses: ['CALL-0918', 'CALL-0826', 'MEM-051', 'MEM-053', 'OPP-504'] }),
      D('missing', 'Assets and flows not in hand', 'Read in parallel from the assets and flows services, alongside the notes.'),
      D('memory', 'Read only', 'Nothing new about Daniel to store.', { class: 'read_only' }),
      D('controls', 'Brief only; nothing sent or booked', 'Read-only: no calendar, email or CRM writes. Follow-ups are proposed, not created.'),
      TK({ id: 'T1', route: 'Prep.Profile', title: 'Profile, book and pipeline', objective: 'Read Daniel’s profile, his CG assets by vehicle and his open opportunity', services: ['assets', 'pipeline'], tools: ['crm.get_contact', 'book.get_assets', 'pipeline.get'], reads: ['memory'], returns: 'Profile, CG assets by vehicle with the prior year, open opportunity', why: 'Profile reads CRM, the assets service and the pipeline together.' }),
      TK({ id: 'T2', route: 'Prep.Notes', title: 'What Daniel told us', objective: 'Summarize Daniel’s dated statements from recorded calls', services: ['memory'], tools: ['crm.get_call_notes'], reads: ['memory'], returns: 'Attributed statements with dates', why: 'Notes Summarizer reads recorded calls in Salesforce.' }),
      TK({ id: 'T3', route: 'Lead.Insights', title: 'What changed in his flows', objective: 'Summarize the year-over-year change in sales and flows by vehicle and channel', services: ['flows'], tools: ['book.get_flows'], reads: ['knowledge'], returns: 'Dated changes, not a full profile repeat', why: 'Insights Generator explains changes from the flows service.' }),
      TK({ id: 'T4', route: 'Prep.Content', title: 'Pick approved content', objective: 'Choose two or three approved pieces that fit what Daniel said and what changed', depends_on: ['T1', 'T2', 'T3'], services: ['approved search'], tools: ['seismic.search_content'], reads: ['knowledge', 'policy'], returns: 'Approved pieces with an advisor-specific reason each', why: 'Content searches approved material only, after the reads tell it what matters.' }),
      TK({ id: 'T5', route: 'Prep.Agenda', title: 'Build the meeting agenda', objective: 'Turn the verified reads and chosen content into a timed agenda for Priya', depends_on: ['T1', 'T2', 'T3', 'T4'], reads: ['memory', 'knowledge', 'policy'], tools: [], returns: 'A timed agenda with what to avoid repeating', why: 'Agenda builds only from verified topics.' }),
      D('success', 'Priya walks in with a timed agenda', 'What changed, what Daniel asked, which approved pieces to bring, and nothing booked or sent.'),
      L({ k: 'end' })
    ].join('\n'),
    agents: {
      T1: { calls: [['crm.get_contact', { advisor_id: 'ADV-105' }], ['book.get_assets', { advisor_id: 'ADV-105' }], ['pipeline.get', { advisor_id: 'ADV-105' }]],
        json: { says: 'I read Daniel’s profile, his CG book by vehicle with last year’s snapshot, and his open opportunity in one pass.',
          output: { kind: 'note', title: 'Profile and CG book: Kim Group', body: 'Daniel Kim, Managing Director, Wells Fargo Advisors; programs: Personalized UMA and Brokerage.\n\nCG assets: $232.0M as of Aug 31, 2026\n- Mutual funds $148.2M (63.9%), ETFs $41.2M (17.8%), SMAs $42.6M (18.4%)\n- A year earlier ETFs were 9.3% of the book and mutual funds 72.2%\n- Largest holdings: GFA F-2 $54.0M, AMBAL F-2 $31.3M\n\nOpen opportunity: OPP-504 Kim Group model refresh, Discovery since Sep 18.' },
          used: ['ADV-105', 'book.get_assets', 'OPP-504'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: ['Aug 31, 2026'], status: 'complete', next_step: '' } },
      T2: { calls: [['crm.get_call_notes', { advisor_id: 'ADV-105' }]],
        json: { says: 'I pulled Daniel’s own words from Sam’s August call and Priya’s September call.', output: NOTES_DANIEL, used: ['CALL-0826', 'CALL-0918', 'MEM-051', 'MEM-053'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: ['Sep 18, 2026'], status: 'complete', next_step: '' } },
      T3: { calls: [['book.get_flows', { advisor_id: 'ADV-105' }]],
        json: { says: 'I summarized what changed in his flows year over year; the model channel is where sales fell.',
          output: { kind: 'finding', title: 'Flows: what changed', body: 'Trailing twelve months to Aug 2026 against the year before:\n- Gross sales $38.2M vs $44.9M (−14.9%)\n- ETF sales up $6.4M; mutual fund sales down $11.7M\n- Model-portfolio channel down $9.5M\n- Net flows $15.2M vs $29.1M as mutual fund redemptions rose' },
          used: ['book.get_flows'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: ['Sep 2025 to Aug 2026'], status: 'complete', next_step: '' } },
      T4: { calls: [['seismic.search_content', { query: 'core satellite etf active index model portfolios' }]],
        json: { says: 'I chose two approved pieces that answer what Daniel has actually raised, each with its reason.',
          output: { kind: 'content_pick', title: 'Approved content for the Kim Group meeting', body: '- SEIS-117 Core-satellite: where active management fits. Why: Daniel moved two models to an index core and reviews the satellites each quarter (CALL-0826, MEM-053)\n- SEIS-120 Capital Group ETF lineup overview. Why: ETFs versus active funds keeps coming up for him (CALL-0918)\n\nBackup: SEIS-114 The Capital System explainer, if he asks how the satellites are managed.' },
          used: ['SEIS-117', 'SEIS-120', 'SEIS-114', 'CALL-0826', 'CALL-0918', 'MEM-053'], knowledge: [], memory: [], commitments: [], needs_approval: false, open_questions: [], as_of: [], status: 'complete', next_step: '' } },
      T5: { calls: [],
        json: { says: 'I turned the verified reads and the chosen content into a timed agenda for Priya; nothing was booked or sent.',
          output: { kind: 'brief', title: 'Agenda: Kim Group, Wed Sep 30', body: 'Goal: help Daniel decide what belongs in the satellites of his refreshed models (OPP-504).\n\n1. What changed: ETFs are now 17.8% of his CG book, up from 9.3%; model-portfolio sales fell $9.5M as two models moved to an index core\n2. His question: where active managers still add value in core-satellite (SEIS-117)\n3. ETF options: what keeps coming up for him, with the ETF lineup (SEIS-120)\n4. Next step: agree which satellite funds he reviews this quarter\n\nAvoid repeating: his priority on a lower blended cost is already recorded (MEM-051).' },
          used: ['OPP-504', 'SEIS-117', 'SEIS-120', 'MEM-051', 'CALL-0826'], knowledge: [], memory: [], commitments: [{ title: 'Send Daniel the two approved pieces as PDFs after the meeting', owner: 'Priya Shah', due: 'Oct 2' }], needs_approval: false,
          open_questions: ['How long is tomorrow’s meeting, and who from the Kim Group attends?'], as_of: ['Aug 31, 2026', 'Sep 18, 2026'], status: 'complete',
          next_step: 'Open with the model refresh (OPP-504) and ask which satellite funds Daniel is reviewing this quarter; bring SEIS-117 and SEIS-120.' } }
    } }
);
